import React from 'react';
import './marquee.css';

function Marquee(props) {
    return (
        <marquee scrolldelay={30} scrollamount="40" className={`marquee ${props.bottom && 'marquee__bottom'}`}>
                $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF
                $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF
                $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF
                $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF
                $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF
                $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF
                $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF
                $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF
                $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF
                $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF
                $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF
                $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF
                $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF
                $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF
                $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF
                $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF
                $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF
                $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF
                $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF
                $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF
                $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF
                $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF
                $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF $DONKWIF
        </marquee>
    );
}

export default Marquee;
