import React from 'react';
import './marquee.css';

function Marquee() {
    return (
        <marquee scrolldelay={30} scrollamount="40" className="marquee">
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
            $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY $DONKEY
        </marquee>
    );
}

export default Marquee;
